Document: scope
Title: Debian scope Manual
Author: <insert document author here>
Abstract: This manual describes what scope is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scope/scope.sgml.gz

Format: postscript
Files: /usr/share/doc/scope/scope.ps.gz

Format: text
Files: /usr/share/doc/scope/scope.text.gz

Format: HTML
Index: /usr/share/doc/scope/html/index.html
Files: /usr/share/doc/scope/html/*.html
